SOURCE_MAP = {
    "fck": "WALL W1!H2 / H169",
    "fy": "WALL W1!H3 / H170",
    "sbc": "WALL W1!H4 / H631",
    "unit_weight_liquid": "WALL W1!H9 / H168 / H630",
    "crack_limit": "WALL W1!H13",
    "wall_top_rl": "WALL W1!H160",
    "water_top_rl": "WALL W1!H161",
    "side_wall_bottom_rl": "WALL W1!H162 = H163 + B646 (approved correction)",
    "raft_top_rl": "WALL W1!H163",
    "liquid_depth": "WALL W1!H164",
    "total_wall_depth": "WALL W1!H167",
    "bm_coefficient": "WALL W1!H171 / H64",
    "wall_cover": "WALL W1!H172",
    "wall_pressure_table": "WALL W1!B178:F189 (water-depth dependency corrected)",
    "wall_reinforcement": "WALL W1!B194:I224",
    "horizontal_reinforcement": "WALL W1!A228:I242",
    "wall_shear": "WALL W1!A246:G331; code-specific shear basis (LSM: IS 456 Table 19; WSM: applicable IS 3370 table)",
    "wall_crack": "WALL W1!A335:I418; hidden intermediate rows reproduced internally",
    "footing_geometry": "WALL W1!C643:G650",
    "stability": "WALL W1!A653:I685",
    "heel_toe_moments": "WALL W1!A697:I718",
    "governing_footing_moment": "WALL W1!E722 (approved MAX(ABS(heel),ABS(toe)) correction)",
    "footing_depth": "WALL W1!H724:H729",
    "footing_reinforcement": "WALL W1!A730:I763",
    "footing_shear": "WALL W1!A765:I799; code-specific shear basis (LSM: IS 456 Table 19; WSM: applicable IS 3370 table)",
    "footing_crack": "WALL W1!A800:I882; H881 linked to H13",
}

CORRECTION_NOTES = [
    "QD-001: side-wall bottom RL now depends on the visible raft RL instead of a hard-coded 1585.45 value.",
    "QD-002: water depth at each wall station is derived from visible wall/water levels using MAX(0, station height - dry height).",
    "QD-003: WALL W1!M200 = #REF! is intentionally ignored per user instruction and is not part of the application engine.",
    "QD-004: wall effective depth uses the largest active tension-bar diameter at the station.",
    "QD-005: governing footing design moment is MAX(ABS(heel moment), ABS(toe moment)).",
    "QD-006: footing top/bottom reinforcement demand is assigned from moment sign rather than assuming fixed heel/toe signs.",
    "QD-007: eccentricity is checked by magnitude; minimum bearing pressure must be non-negative.",
    "QD-008: footing top and bottom effective depths are calculated separately from the active reinforcement layers.",
    "QD-009: footing crack-width limit uses the same visible crack-width input as the wall check.",
    "QD-010: the application scope is locked to the visible Inside Liquid Pressure W1/W1A case.",
    "QD-011: capacity checks accept equality (<= / >= as appropriate).",
    "Engine reconciliation: manually copied downstream required-steel values are replaced by live dependencies.",
    "Engine reconciliation: LSM shear uses proper piecewise IS 456:2000 Table 19 interpolation; legacy WSM branches use the applicable IS 3370 permissible-shear table.",
]
